### ISSUE TITLE
有部分python2的代码无法运行

### ISSUE THREAD

**Issue by mkbk-with-circle** [netiken/m3#2]
<img width="860" alt="截屏2024-09-25 09 00 31" src="https://github.com/user-attachments/assets/fcb277c8-900d-47fa-8acb-bfc68d3f7475">
在这一步中，有部分脚本是用python2的语法，似乎无法直接运行，但是如果另外用conda创建一个python2的环境，那么requirement里的部分包又无法配置，请问您有什么解决方法吗？感谢！

**Comment by liecn** [comment]
Here are two possible solutions:

1. Set up a Python 2.7 environment specifically for running ns-3 and generating the ground truth.
2. Modify the Python scripts that are written in Python 2 syntax (mostly the `print` statements).

**Comment by mkbk-with-circle** [comment]
> 以下是两种可能的解决方案：
> 
> 1. 专门设置一个 Python 2.7 环境用于运行 ns-3 并生成基本事实。
> 2. 修改用 Python 2 语法编写的 Python 脚本（主要是`print`语句）。

好的，感谢！！！

**Comment by mkbk-with-circle** [comment]
提供一下我自己的解决方法
基本上就是把print语法修改，以及捕获exception时的语法改一改
另外有一个问题就是：
```html
AttributeError: Can't pickle local object 'Context.__init__.<locals>.node_class'
```
查阅相关资料后发现这个因为node_class是一个内部定义的类，无法进行定位进而序列化，因此在`m3/parsimon/backends/High-Precision-Congestion-Control/simulation/.waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Context.py`文件中
我的做法是将Context类中的class node_class放到外面来，并且删去
```py
self.node_class.__module__ = "waflib.Node"
```
<img width="356" alt="截屏2024-09-27 10 37 03" src="https://github.com/user-attachments/assets/e3e407a0-0b61-4f86-b200-e8159db40599">

此时可以顺利运行命令
```html
CC='gcc-5' CXX='g++-5' ./waf configure --build-profile=optimized
```
