### ISSUE TITLE
Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by mkbk-with-circle** [netiken/m3#3]
<img width="620" alt="截屏2024-09-27 10 58 14" src="https://github.com/user-attachments/assets/2e452b6f-cf64-441c-940b-75fe39dcc4cb">
您好！
请问为什么我按照您的配置流程到了
<img width="705" alt="截屏2024-09-27 11 01 00" src="https://github.com/user-attachments/assets/1cf5880d-d838-4385-bb72-f581cd281f11">
这一步时运行命令

```linux
cargo run --release -- --root=./data --mixes spec/all_dctcp.mix.json ns3-config
```
会报错说找不到文件呢？

**Comment by liecn** [comment]
Please confirm which files are missing first. It could be the config file expts/fig_8/spec/all_dctcp.mix.json.

**Comment by mkbk-with-circle** [comment]
配置文件expts/fig_8/spec/all_dctcp.mix.json已有，似乎是缺少ns3-config?

**Comment by liecn** [comment]
ns3-config is an argument, not a file. Please review the script expts/fig_8/src/experiment.rs to identify which files might be missing. For instance, check the target directory NS3_DIR: &str = "../../../parsimon/backends/High-Precision-Congestion-Control/simulation" used in the experiment.rs script.

For your information, these steps have been tested by the artifact reviewers.

**Comment by mkbk-with-circle** [comment]
好的，感谢您的帮助！

**Comment by mkbk-with-circle** [comment]
您好，我用gdb运行脚本“m3/parsimon-eval/target/release/sensitivity-analysis”发现找不到的文件的路径是
 “../sysdeps/x86/abi-note.c”
 请问我该如何解决🥲

**Comment by liecn** [comment]
I haven't encountered this error before. I doubt it's related to Rust. Could you please double-check your Rust installation and try rebuilding the program?

Also, could you test Parsimon and m3 with different arguments?

**Comment by mkbk-with-circle** [comment]
About Rust , I just follow the command of  direction which is:

```linux
# Install Rust and Cargo, https://www.rust-lang.org/tools/install
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# setup the path and check the installation using rustc --version. Then switch to nightly version
rustup install nightly
rustup default nightly
```
and there is no error.But I will still take a shot to reinstall one.

And could you please tell me some details of `test Parsimon and m3 with different arguments?` , I don't quite understand what you mean. Sorry , I am a newbee in such area and again thanks for your help!

**Comment by liecn** [comment]
Np, try these two commands.

cargo run --release -- --root=./data --mixes spec/all_dctcp.mix.json pmn-m
cargo run --release -- --root=./data --mixes spec/all_dctcp.mix.json mlsys

**Comment by mkbk-with-circle** [comment]
Good news!! These two commands bring no errors!

**Comment by mkbk-with-circle** [comment]
Bad news, I still can't run 

```html
cargo run --release -- --root=./data --mixes spec/all_dctcp.mix.json ns3-config
```

**Comment by liecn** [comment]
Great to hear! So there are no issues with Rust. There might be a problem with the ns-3 setup.

My guess is that the Rust program is calling Python 2 to run the "run.py" script. Can you check to make sure Python 2 and this script are working properly? See the code below.

Since you used Python 3 before, you'll likely need to change the command to python (instead of python2) to run the "run.py" script.

https://github.com/netiken/parsimon-eval/blob/7378a029efb1e6ce35e2f964306992e82671f0c2/expts/fig_8/src/ns3.rs#L119

**Comment by mkbk-with-circle** [comment]
OK I will try later ! Since you are still awake , I shall say ——"国庆快乐！！"

**Comment by mkbk-with-circle** [comment]
<img width="726" alt="截屏2024-10-01 01 07 53" src="https://github.com/user-attachments/assets/33b05a15-0d1b-47b8-9fec-142e1b177764">
I change the command from 'python' to 'python3' or 'python2' but neither works. And I insert two command in the line 126 like:

```rust
.arg(format!("echo 1;cd {ns3_dir};echo 2;  {python_command}; rm {data_dir}/flows.txt"))
``` 
to print some debug info.Then I find it seems that the program even doesn't enter execute to the command 'python2 run.py'?

**Comment by liecn** [comment]
Could you try debugging the Rust code using breakpoints? That might help identify where the issue is.

**Comment by mkbk-with-circle** [comment]
OK , I will do that tomorrow . You are so nice a man ! Good night !

**Comment by canbringyouback** [comment]
Following because I have same issue🥲.

**Comment by liecn** [comment]
Hi,

I've tested ns-3 on my end, and to compile it successfully in m3, you need to use the following command:

```
CC='gcc-5' CXX='g++-5' CXXFLAGS='-std=c++11' ./waf configure --build-profile=optimized
```

I’ve made two updates:

1. Updated the README with the correct compilation instructions for ns-3.
2. Reduced the number of testing configurations in m3/parsimon-eval/expts/fig_8/spec/all_dctcp.mix.json from 5 to 1. Since ns-3 needs to be built before the first run, launching 5 configurations initially might cause issues.

Please check the ns-3 simulation results in m3/parsimon-eval/expts/fig_8/data/0/ns3-config/2/fct_topology_flows_dctcp.txt.

**Comment by mkbk-with-circle** [comment]
哇塞，太感谢您了！我明天早市就去试试！

**Comment by mkbk-with-circle** [comment]
Sorry , I follow your instruction and create a totally new remote cloudlab enviroment trying to complete the whole process again.But I still meet the question when executing the command:


```linux
cargo run --release -- --root=./data --mixes spec/all_dctcp.mix.json ns3-config
```
and thus the file `m3/parsimon-eval/expts/fig_8/data/0/ns3-config/2/fct_topology_flows_dctcp.txt.` doesn't exist. 
It's really confused. I wonder if it is because the different os we use? 
<img width="472" alt="截屏2024-10-02 22 41 10" src="https://github.com/user-attachments/assets/fd40b7fc-63e4-4722-bb1e-83a580009d1d">
This is the configuration of my remote environment.

**Comment by liecn** [comment]
The OS should work as long as you're able to install gcc-5.

It seems there may be an issue with the HPCC codebase setup. m3 uses HPCC codebase to run ns-3. (https://github.com/alibaba-edu/High-Precision-Congestion-Control)

Can you check if the directory m3/parsimon-eval/expts/fig_8/data/0/ns3-config/2/ exists? You should find the bug details in m3/parsimon-eval/expts/fig_8/data/0/ns3-config/2/output.txt.

Please use that information to debug the issue.

**Comment by mkbk-with-circle** [comment]
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from consts import CC_LIST, PARAM_LIST, CONFIG_TO_PARAM_DICT, DEFAULT_PARAM_VEC
  File "/users/ymy_yuan/m3/parsimon/backends/High-Precision-Congestion-Control/simulation/consts.py", line 1, in <module>
    import numpy as np
ImportError: No module named numpy


I find this info, but how can it be that the process can‘t find numpy 😱😱😱 So strange. I am sure I have open the conda environment.
<img width="821" alt="截屏2024-10-02 23 13 22" src="https://github.com/user-attachments/assets/f4bbfe3a-1cab-4c10-942c-4b336a11b0be">

**Comment by liecn** [comment]
Great! Now that you have more information for debugging, please ensure you are using the correct Python path.

When I tested this yesterday, I created a new Python 2.7 environment, installed NumPy, and then ran the following command under Python 2.7:

CC='gcc-5' CXX='g++-5' CXXFLAGS='-std=c++11' ./waf configure --build-profile=optimized

Afterward, I used the command:

cargo run --release -- --root=./data --mixes spec/all_dctcp.mix.json ns3-config

This setup worked for me.

Let me know if you need any further assistance!

**Comment by liecn** [comment]
> <img alt="截屏2024-10-01 01 07 53" width="726" src="https://private-user-images.githubusercontent.com/121886433/372178291-33b05a15-0d1b-47b8-9fec-142e1b177764.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODI0MzEsIm5iZiI6MTcyNzg4MjEzMSwicGF0aCI6Ii8xMjE4ODY0MzMvMzcyMTc4MjkxLTMzYjA1YTE1LTBkMWItNDdiOC05ZmVjLTE0MmUxYjE3Nzc2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxNTE1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2JjOGUzMGViZjk1MGY2MDIwZmNkNjZmOThlYTRiYzVkMzM3YzZiM2JjM2YzYzczZGE5MTJiMzRhODU0MGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ISbHnxahZO2TT3d547JqK2H9JIJqx_inc9O5icI7dNY"> I change the command from 'python' to 'python3' or 'python2' but neither works. And I insert two command in the line 126 like:
> ```rust
> .arg(format!("echo 1;cd {ns3_dir};echo 2;  {python_command}; rm {data_dir}/flows.txt"))
> ```
> 
> to print some debug info.Then I find it seems that the program even doesn't enter execute to the command 'python2 run.py'?

Please ensure you're using the correct Python version.

**Comment by mkbk-with-circle** [comment]
Emm, It seems to be the key of the solution to my error. So I need to confirm whether the whole   project is running in python3 or python2 ? I am always in python3 , python2 is also installed but  is only used in the command: `CC='gcc-5' CXX='g++-5' CXXFLAGS='-std=c++11' ./waf configure --build-profile=optimized` . Is that true?

**Comment by liecn** [comment]
> > <img alt="截屏2024-10-01 01 07 53" width="726" src="https://private-user-images.githubusercontent.com/121886433/372178291-33b05a15-0d1b-47b8-9fec-142e1b177764.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODI0MzEsIm5iZiI6MTcyNzg4MjEzMSwicGF0aCI6Ii8xMjE4ODY0MzMvMzcyMTc4MjkxLTMzYjA1YTE1LTBkMWItNDdiOC05ZmVjLTE0MmUxYjE3Nzc2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxNTE1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2JjOGUzMGViZjk1MGY2MDIwZmNkNjZmOThlYTRiYzVkMzM3YzZiM2JjM2YzYzczZGE5MTJiMzRhODU0MGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ISbHnxahZO2TT3d547JqK2H9JIJqx_inc9O5icI7dNY"> I change the command from 'python' to 'python3' or 'python2' but neither works. And I insert two command in the line 126 like:
> > ```rust
> > .arg(format!("echo 1;cd {ns3_dir};echo 2;  {python_command}; rm {data_dir}/flows.txt"))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to print some debug info.Then I find it seems that the program even doesn't enter execute to the command 'python2 run.py'?
> 
> Please ensure you're using the correct Python version.

As you can see, m3 uses the original setup from HPCC, which runs run.py with Python 2 (as shown above on line 119). For consistency, I also used Python 2 to compile ns-3, although I don’t think it makes a big difference. You can compile with Python 3 if you prefer, but be sure you're using the correct Python path when running run.py in the Rust scripts (as shown above on line 119).

**Comment by mkbk-with-circle** [comment]
好消息！好消息！好消息！好消息！
<img width="794" alt="截屏2024-10-02 23 40 33" src="https://github.com/user-attachments/assets/b632f437-9327-405c-ad4a-e90060363a23">
现在似乎是跑起来了，虽然还没停止，但是ns3-config/2文件夹里已经不止原来的output.txt和topology.txt了！！！请问这是成功的表现吗？！

**Comment by liecn** [comment]
If the file `m3/parsimon-eval/expts/fig_8/data/0/ns3-config/2/fct_topology_flows_dctcp.txt` is continuously updating, it means everything is working correctly.

Each line in the file represents a completed flow.

**Comment by mkbk-with-circle** [comment]
OK！My question is finally over ! Sincerely thanks for your help ! And I also recommend you add the solution to the README.md in case others meet the same situation! Wish you good days!

**Comment by liecn** [comment]
Updated already. Thanks.

**Comment by mkbk-with-circle** [comment]
You are my hero ! See you !
