### ISSUE TITLE
Summary of optional NS-3 features: not enabled

### ISSUE THREAD

**Issue by mkbk-with-circle** [netiken/m3#4]
您好，请问我在执行了

```html
CC='gcc-5' CXX='g++-5' ./waf configure --build-profile=optimized
```
这句命令之后显示
<img width="636" alt="截屏2024-09-30 10 26 58" src="https://github.com/user-attachments/assets/e7535ff6-d9fc-484a-b58f-68923aa97dfb">
请问这是正常的嘛，以及是否会影响后续的运行

**Comment by liecn** [comment]
This seems good to me.

**Comment by mkbk-with-circle** [comment]
ok , thanks for your help!
