### ISSUE TITLE
关于flowsim算法的实现

### ISSUE THREAD

**Issue by mkbk-with-circle** [netiken/m3#5]
你好，非常抱歉再次打扰你
我在仔细研究您的代码及有关的论文的时候，阅读到了flowsim算法（如下图），但是在您`m3/util/dataset.py`中我似乎并没有找到非常符合flowsim算法的实现（比如说建立优先队列及调度），请问您是否有具体实现呢？
<img width="343" alt="截屏2024-10-24 21 49 45" src="https://github.com/user-attachments/assets/83794206-8ced-4b7f-93e7-7a80c117d145">
另外还有一个问题，同样也是在`m3/util/dataset.py`中，似乎在计算ICT（理论流完成时间）的时候没有考虑不同流之间对于带宽的竞争？可否请您解答一下！

再次感谢！！

**Comment by liecn** [comment]
Hi,

Please take a look at the code in `m3/parsimon/backends/High-Precision-Congestion-Control/analysis/main_flowsim_mmf.py`, where a C function is used to run `flowSim`.

Additionally, the **ideal flow completion time** refers to the time it takes for a flow of that size to complete in an **unloaded network**.

Lastly, could you please leave your questions in English so more people can benefit? Also, checking the code before posting questions will help save a lot of communication time. 🙂

Thanks!

**Comment by mkbk-with-circle** [comment]
Really thanks for your help. I apologize for it that I am always focusing on the dataset.py to find sth about flowsim and doesn't try to think of other files.Next time I will check the code firstly!
