### ISSUE TITLE
why to use extend()

### ISSUE THREAD

**Issue by mkbk-with-circle** [netiken/m3#7]
I hope this message finds you well. I’m currently reviewing the code in m3/parsimon-eval/expts/fig_8/src/experiment.rs and came across the following line at line 513:
```rust
flows_remaining.extend(flow_extra);
```
I would greatly appreciate it if you could provide some insight into the specific purpose of the extend function in this context.

**Comment by liecn** [comment]
Hi,

Thanks for your question.

From lines 470 to 515, I mapped the path for each flow from the full topology to a single path. For instance, a path defined in the full topology as `[(5, 256), (256, 289), (289, 264), (264, 16)]` (where each number represents a node ID and a pair of node IDs defines a link) is represented in the path topology as `[(0, 1), (1, 2), (2, 3), (3, 4)]`. This rearranges the node IDs to match the path topology.

Everything works fine if a flow traverses the target path only once. However, some background flows traverse the path multiple times. For example, a background flow might traverse links `(0, 1)` and `(3, 4)` in the path topology. This means that when converting the flows from the full topology to the path topology, some flows effectively behave like multiple flows.

To handle this, in lines 470 to 490, I first check if a flow traverses the path only once. If not (e.g., it traverses the path N times), in lines 500 to 512, I create N-1 additional flows to mimic the flow's behavior.

Let me know if you need further clarification!

**Comment by mkbk-with-circle** [comment]
OK , Thanks for your patient answer! Wish you good days!
